name: DoubleMint
version: '${project.version}'
main: org.lime.doublemint.Main
api-version: 1.17
authors: [ LimeEdits ]
commands:
  Feed:
    description: Fills Your Hunger
    usage: /<command>
    aliases:
      - feed
      - Feed
      - eat
      - Eat

  Token:
    description: Token Gui
    usage: /<Command>
    aliases:
      - Tokens
      - tokens
      - token

  armorstand:
    description: Create a armor stand
    usage: /<command>
    aliases:
      - as
  hologram:
    description: Spawn a Hologrm
    usage: /<command>
    aliases:
      - Hologram
      - holograms
      - Holograms
  sign:
    description: spawna  sign
    usage: /<command>

